bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: marine-potion-312409
      dataset: analysis
      threads: 1
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
